djProjHomrBuhWeb/djProjHomrBuhWeb/urls.py
from django.contrib import admin
from django.urls import include, path

from djProjHomrBuhWeb import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homebuhweb.urls')),
]

djProjHomrBuhWeb/homebuhweb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from .views import user_cabinet, get_currency_rates_view

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('user_cabinet/', user_cabinet, name='user_cabinet'),
    path('get_currency_rates/', get_currency_rates_view, name='get_currency_rates'),
    path('user_prof/', views.user_prof, name='user_prof'),
    path('delete_avatar/', views.delete_avatar, name='delete_avatar'),
    path('logout/', auth_views.LogoutView.as_view(next_page='homepage'), name='logout'),
    path('incomes/add/', views.add_income, name='add_income'),
    path('incomes/edit/<int:id>/', views.add_income, name='edit_income'),
    path('incomes/delete/<int:id>/', views.delete_income, name='delete_income'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/edit/<int:expense_id>/', views.edit_expense, name='edit_expense'),
    path('get_subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),
    path('get_subsubcategories/<int:subcategory_id>/', views.get_subsubcategories, name='get_subsubcategories'),
    path('expenses/delete/<int:expense_id>/', views.delete_expense, name='delete_expense'),
    path('add_car_expense/<int:expense_id>/', views.add_car_expense, name='add_car_expense'),
    path('plan_expenses/', views.plan_expenses, name='plan_expenses'),
    path('add_planned_expense.html/', views.add_planned_expense, name='add_planned_expense'),
    path('edit_planned_expense/<int:pk>/', views.edit_planned_expense, name='edit_planned_expense'),
    path('delete_planned_expense/<int:pk>/', views.delete_planned_expense, name='delete_planned_expense'),
    path('credit/add/', views.add_credit, name='add_credit'),
    path('credit/edit/<int:pk>/', views.edit_credit, name='edit_credit'),
    path('credit/delete/', views.delete_credit, name='delete_credit'),
    path('diagrams/', views.show_grafics, name='show_grafics'),
path('car_expense_report/', views.car_expense_report, name='car_expense_report'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djProjHomrBuhWeb/homebuhweb/models.py
from decimal import Decimal

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username


class Income(models.Model):
    INCOME_TYPES = [
        ('заработная плата', 'Заработная плата'),
        ('пенсия', 'Пенсия'),
        ('стипендия', 'Стипендия'),
        ('выигрыш', 'Выигрыш'),
        ('доходы от индивидуальной предпринимательской деятельности',
         'Доходы от индивидуальной предпринимательской деятельности'),
        ('доходы от недвижимости', 'Доходы от недвижимости'),
        ('доходы от депозита', 'Доходы от депозита'),
        ('подарки', 'Подарки'),
        ('наличные денежные средства', 'Наличные денежные средства'),
        ('прочие доходы', 'Прочие доходы'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    income_type = models.CharField(max_length=100, choices=INCOME_TYPES)
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))])
    date = models.DateField()

    def __str__(self):
        return f"{self.income_type} - {self.amount}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class SubSubCategory(models.Model):
    name = models.CharField(max_length=100)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    subsubcategory = models.ForeignKey(SubSubCategory, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return f"{self.category} - {self.subcategory} - {self.subsubcategory} - {self.amount}"


class CarExpense(models.Model):
    car_brand = models.CharField(max_length=100)
    mileage = models.PositiveIntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=250)
    date = models.DateField()
    subsubcategory = models.ForeignKey(Expense, on_delete=models.CASCADE, related_name='car_expenses')

    def __str__(self):
        return f"{self.car_brand} - {self.amount}"


class PlannedExpense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=255)
    start_date = models.DateField()

    item_cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))]
    )

    months_to_save = models.IntegerField(
        validators=[MinValueValidator(1)]
    )

    monthly_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True
    )

    def calculate_monthly_amount(self):
        if self.months_to_save > 0:
            return self.item_cost / self.months_to_save
        return Decimal('0.00')

    def save(self, *args, **kwargs):
        self.monthly_amount = self.calculate_monthly_amount()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.item_name} - {self.item_cost}"


class Credit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    credit_name = models.CharField(max_length=255)
    credit_amount = models.PositiveIntegerField()
    credit_term = models.IntegerField()
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    issue_date = models.DateField()

    def __str__(self):
        return self.credit_name

    @property
    def principal_amount(self):
        return Decimal(self.credit_amount) / Decimal(self.credit_term)

    @property
    def monthly_interest(self):
        return (Decimal(self.credit_amount) * (self.interest_rate / Decimal(100))) / Decimal(12)

    @property
    def monthly_payment(self):
        return self.principal_amount + self.monthly_interest

djProjHomrBuhWeb/homebuhweb/views.py
import base64
import datetime
import io
import textwrap
import urllib.parse
from datetime import date, timedelta, datetime
from decimal import Decimal, ROUND_HALF_UP

import matplotlib.pyplot as plt
import pandas as pd
import requests
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import Group
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.templatetags.static import static
from django.views.decorators.csrf import csrf_protect

from .forms import CreditForm, ExpenseForm, CarExpenseForm, PlannedExpenseForm, UserForm, ProfileForm
from .models import Category, SubCategory, SubSubCategory, CarExpense, Credit, Expense, Income, Profile, PlannedExpense


def homepage(request):
    return render(request, 'homebuhweb/homepage.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='Users')
            user.groups.add(group)
            login(request, user)
            return redirect('user_cabinet')
    else:
        form = UserCreationForm()
    return render(request, 'homebuhweb/login/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('user_cabinet')
        else:
            messages.error(request, "Такого пользователя не существует или неверный пароль.")
            return redirect('homepage')
    else:
        form = AuthenticationForm()
        return render(request, 'homebuhweb/homepage.html', {'form': form})


def calculate_balance(user):
    incomes = Income.objects.filter(user=user)
    expenses = Expense.objects.filter(user=user)

    total_income = incomes.aggregate(Sum('amount'))['amount__sum'] or 0
    total_expenses = expenses.aggregate(Sum('amount'))['amount__sum'] or 0
    balance = total_income - total_expenses

    return total_income, total_expenses, balance


@login_required
def user_cabinet(request):
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    total_income = Decimal('0.00')
    total_income_usd = Decimal('0.00')
    total_income_eur = Decimal('0.00')
    total_income_rub = Decimal('0.00')
    credits = Credit.objects.filter(user=request.user)
    total_monthly_payments = sum(credit.monthly_payment for credit in credits)
    total_income, total_expenses, balance = calculate_balance(request.user)

    user = request.user
    profile = get_object_or_404(Profile, user=user)

    # Initialize forms
    user_form = UserForm(instance=user)
    profile_form = ProfileForm(instance=profile)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

    # Default currency rates
    usd_rate = Decimal('1')
    eur_rate = Decimal('1')
    rub_rate = Decimal('1')

    if start_date and end_date:
        start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
        end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
        incomes = Income.objects.filter(
            user=request.user, date__range=[start_date, end_date]
        )
        total_income = sum(income.amount for income in incomes)

    # Get current currency rates
    currency_rates = get_currency_rates()
    if 'error' not in currency_rates:
        usd_rate = currency_rates.get('USD', Decimal('1'))
        eur_rate = currency_rates.get('EUR', Decimal('1'))
        rub_rate = currency_rates.get('RUB', Decimal('1'))

    # Convert income to different currencies
    total_income_usd = (total_income / usd_rate).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )
    total_income_eur = (total_income / eur_rate).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )
    total_income_rub = (total_income / (rub_rate / Decimal('100'))).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )

    expenses = PlannedExpense.objects.filter(user=request.user)
    total_monthly_amount = Decimal('0.00')
    for expense in expenses:
        total_monthly_amount += expense.calculate_monthly_amount()
    total_monthly_amount = total_monthly_amount.quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )

    # Convert planned expenses to different currencies
    total_monthly_amount_usd = (total_monthly_amount / usd_rate).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )
    total_monthly_amount_eur = (total_monthly_amount / eur_rate).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )
    total_monthly_amount_rub = (
            total_monthly_amount / (rub_rate / Decimal('100'))
    ).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

    # Convert credit payments to different currencies
    total_monthly_payments_usd = (total_monthly_payments / usd_rate).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )
    total_monthly_payments_eur = (total_monthly_payments / eur_rate).quantize(
        Decimal('0.01'), rounding=ROUND_HALF_UP
    )
    total_monthly_payments_rub = (
            total_monthly_payments / (rub_rate / Decimal('100'))
    ).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

    return render(
        request,
        'homebuhweb/login/usercabinet.html',
        {
            'start_date': start_date,
            'end_date': end_date,
            'total_income': total_income,
            'total_income_usd': total_income_usd,
            'total_income_eur': total_income_eur,
            'total_income_rub': total_income_rub,
            'total_expenses': total_expenses,
            'total_monthly_amount': total_monthly_amount,
            'total_monthly_amount_usd': total_monthly_amount_usd,
            'total_monthly_amount_eur': total_monthly_amount_eur,
            'total_monthly_amount_rub': total_monthly_amount_rub,
            'total_monthly_payments': total_monthly_payments,
            'total_monthly_payments_usd': total_monthly_payments_usd,
            'total_monthly_payments_eur': total_monthly_payments_eur,
            'total_monthly_payments_rub': total_monthly_payments_rub,
            'balance': balance,
            'balance_value': balance,
            'user_form': user_form,
            'profile_form': profile_form,
            'avatar_url': (
                profile.avatar.url if profile.avatar else static('images/apple-touch-icon.png')
            ),
            'username': user.get_full_name() or user.username,
        },
    )


def get_currency_rates():
    url = 'https://www.nbrb.by/api/exrates/rates?periodicity=0'
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        rates = {}
        currencies = ['USD', 'EUR', 'RUB']
        for rate in data:
            if rate['Cur_Abbreviation'] in currencies:
                rates[rate['Cur_Abbreviation']] = Decimal(str(rate['Cur_OfficialRate']))

        return rates
    except requests.exceptions.RequestException as e:
        return {'error': 'Ошибка при получении данных от API: ' + str(e)}
    except ValueError as e:
        return {'error': 'Ошибка обработки данных: ' + str(e)}


@login_required
def get_currency_rates_view(request):
    rates = get_currency_rates()
    return JsonResponse(rates)


@login_required
def user_prof(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user_prof')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    return render(request, 'homebuhweb/login/user_prof.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def delete_avatar(request):
    user = request.user
    user.profile.avatar.delete()
    return redirect('user_prof')


@login_required
def add_income(request, id=None):
    if id:
        income = get_object_or_404(Income, id=id, user=request.user)
    else:
        income = None

    if request.method == 'POST':
        income_type = request.POST['income_type']
        amount = request.POST['amount']
        date = request.POST['date']

        if income:
            income.income_type = income_type
            income.amount = amount
            income.date = date
            income.save()
        else:
            Income.objects.create(
                user=request.user,
                income_type=income_type,
                amount=amount,
                date=date
            )

        return redirect('add_income')

    sort_by = request.GET.get('sort', 'date')
    incomes = Income.objects.filter(user=request.user).order_by(sort_by)
    total_income = incomes.aggregate(Sum('amount'))['amount__sum'] or 0

    return render(
        request,
        'homebuhweb/incomes/add_income.html',
        {
            'income': income,
            'incomes': incomes,
            'total_income': total_income
        }
    )


@login_required
def delete_income(request, id):
    income = get_object_or_404(Income, id=id)
    income.delete()
    return redirect('add_income')


@login_required
def add_expense(request):

djProjHomrBuhWeb/templates/homebuhweb/incomes/add_income.html
{% extends 'homebuhweb/base.html' %}

{% block content %}
    <div class="container">
        <h2>{% if income %}Редактировать доход{% else %}Добавить доход{% endif %}</h2>
        <form method="POST">
            {% csrf_token %}
            <!-- Поле для выбора вида дохода -->
            <div class="mb-3">
                <label for="id_income_type" class="form-label">Выбрать вид дохода:</label>
                <select name="income_type" class="form-control" id="id_income_type" required>
                    <option value="заработная плата"
                            {% if income and income.income_type == "заработная плата" %}selected{% endif %}>Заработная
                        плата
                    </option>
                    <option value="пенсия" {% if income and income.income_type == "пенсия" %}selected{% endif %}>
                        Пенсия
                    </option>
                    <option value="стипендия" {% if income and income.income_type == "стипендия" %}selected{% endif %}>
                        Стипендия
                    </option>
                    <option value="выигрыш" {% if income and income.income_type == "выигрыш" %}selected{% endif %}>
                        Выигрыш
                    </option>
                    <option value="доходы от индивидуальной предпринимательской деятельности"
                            {% if income and income.income_type == "доходы от индивидуальной предпринимательской деятельности" %}selected{% endif %}>
                        Доходы от индивидуальной предпринимательской деятельности
                    </option>
                    <option value="доходы от недвижимости"
                            {% if income and income.income_type == "доходы от недвижимости" %}selected{% endif %}>Доходы
                        от недвижимости
                    </option>
                    <option value="доходы от депозита"
                            {% if income and income.income_type == "доходы от депозита" %}selected{% endif %}>Доходы от
                        депозита
                    </option>
                    <option value="подарки" {% if income and income.income_type == "подарки" %}selected{% endif %}>
                        Подарки
                    </option>
                    <option value="наличные денежные средства"
                            {% if income and income.income_type == "наличные денежные средства" %}selected{% endif %}>
                        Наличные денежные средства
                    </option>
                    <option value="прочие доходы"
                            {% if income and income.income_type == "прочие доходы" %}selected{% endif %}>Прочие доходы
                    </option>
                </select>
            </div>
            <!-- Поле для суммы -->
            <div class="mb-3">
                <label for="id_amount" class="form-label">Сумма:</label>
                <input type="number" name="amount" class="form-control" id="id_amount"
                       value="{% if income %}{{ income.amount }}{% endif %}" min="0" step="0.01" required>
            </div>
            <!-- Поле для выбора даты -->
            <div class="mb-3">
                <label for="id_date" class="form-label">Дата:</label>
                <input type="date" name="date" class="form-control" id="id_date"
                       value="{% if income %}{{ income.date|date:'Y-m-d' }}{% endif %}" required>
            </div>
            <button type="submit" class="btn btn-custom">{% if income %}Сохранить{% else %}Добавить{% endif %}</button>
            <a href="{% url 'user_cabinet' %}" class="btn btn-custom">Возврат в личный кабинет</a>
        </form>
        <!-- Общая сумма доходов -->
        <h2>Общая сумма доходов: {{ total_income }}</h2>
        <!-- Таблица доходов -->
        <h2>Список доходов</h2>
        <table class="table table-striped">
            <thead>
            <tr>
                <th><a href="?sort=income_type" style="color: black; text-decoration: none;">Вид дохода</a></th>
                <th><a href="?sort=amount" style="color: black; text-decoration: none;">Сумма дохода</a></th>
                <th><a href="?sort=date" style="color: black; text-decoration: none;">Дата дохода</a></th>
                <th>Операции над доходами</th>
            </tr>
            </thead>
            <tbody>
            {% for income in incomes %}
                <tr>
                    <td>{{ income.income_type }}</td>
                    <td>{{ income.amount }}</td>
                    <td>{{ income.date|date:'d.m.Y' }}</td>
                    <td>
                        <a href="{% url 'edit_income' income.id %}" class="btn btn-warning">Изменить</a>
                        <a href="{% url 'delete_income' income.id %}" class="btn btn-danger">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}