djProjHomrBuhWeb/djProjHomrBuhWeb/urls.py
from django.contrib import admin
from django.urls import include, path

from djProjHomrBuhWeb import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homebuhweb.urls')),
]

djProjHomrBuhWeb/homebuhweb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from .views import user_cabinet, get_currency_rates_view

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('user_cabinet/', user_cabinet, name='user_cabinet'),
    path('get_currency_rates/', get_currency_rates_view, name='get_currency_rates'),
    path('user_prof/', views.user_prof, name='user_prof'),
    path('delete_avatar/', views.delete_avatar, name='delete_avatar'),
    path('logout/', auth_views.LogoutView.as_view(next_page='homepage'), name='logout'),
    path('incomes/add/', views.add_income, name='add_income'),
    path('incomes/edit/<int:id>/', views.add_income, name='edit_income'),
    path('incomes/delete/<int:id>/', views.delete_income, name='delete_income'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/edit/<int:expense_id>/', views.edit_expense, name='edit_expense'),
    path('get_subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),
    path('get_subsubcategories/<int:subcategory_id>/', views.get_subsubcategories, name='get_subsubcategories'),
    path('expenses/delete/<int:expense_id>/', views.delete_expense, name='delete_expense'),
    path('add_car_expense/<int:expense_id>/', views.add_car_expense, name='add_car_expense'),
    path('plan_expenses/', views.plan_expenses, name='plan_expenses'),
    path('add_planned_expense.html/', views.add_planned_expense, name='add_planned_expense'),
    path('edit_planned_expense/<int:pk>/', views.edit_planned_expense, name='edit_planned_expense'),
    path('delete_planned_expense/<int:pk>/', views.delete_planned_expense, name='delete_planned_expense'),
    path('credit/add/', views.add_credit, name='add_credit'),
    path('credit/edit/<int:pk>/', views.edit_credit, name='edit_credit'),
    path('credit/delete/', views.delete_credit, name='delete_credit'),
    path('diagrams/', views.show_grafics, name='show_grafics'),
path('car_expense_report/', views.car_expense_report, name='car_expense_report'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homebuhweb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from .views import user_cabinet, get_currency_rates_view

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('user_cabinet/', user_cabinet, name='user_cabinet'),
    path('get_currency_rates/', get_currency_rates_view, name='get_currency_rates'),
    path('user_prof/', views.user_prof, name='user_prof'),
    path('delete_avatar/', views.delete_avatar, name='delete_avatar'),
    path('logout/', auth_views.LogoutView.as_view(next_page='homepage'), name='logout'),
    path('incomes/add/', views.add_income, name='add_income'),
    path('incomes/edit/<int:id>/', views.add_income, name='edit_income'),
    path('incomes/delete/<int:id>/', views.delete_income, name='delete_income'),
    path('expenses/add/', views.add_expense, name='add_expense'),
    path('expenses/edit/<int:expense_id>/', views.edit_expense, name='edit_expense'),
    path('get_subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),
    path('get_subsubcategories/<int:subcategory_id>/', views.get_subsubcategories, name='get_subsubcategories'),
    path('expenses/delete/<int:expense_id>/', views.delete_expense, name='delete_expense'),
    path('add_car_expense/<int:expense_id>/', views.add_car_expense, name='add_car_expense'),
    path('plan_expenses/', views.plan_expenses, name='plan_expenses'),
    path('add_planned_expense.html/', views.add_planned_expense, name='add_planned_expense'),
    path('edit_planned_expense/<int:pk>/', views.edit_planned_expense, name='edit_planned_expense'),
    path('delete_planned_expense/<int:pk>/', views.delete_planned_expense, name='delete_planned_expense'),
    path('add/', views.add_credit, name='add_credit'),
    path('edit/<int:pk>/', views.edit_credit, name='edit_credit'),
    path('delete/', views.delete_credit, name='delete_credit'),
    path('mark_as_paid_off/<int:pk>/', views.mark_as_paid_off, name='mark_as_paid_off'),
    path('diagrams/', views.show_grafics, name='show_grafics'),
    path('car_expense_report/', views.car_expense_report, name='car_expense_report'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djProjHomrBuhWeb/homebuhweb/models.py
from decimal import Decimal

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username


class Income(models.Model):
    INCOME_TYPES = [
        ('заработная плата', 'Заработная плата'),
        ('пенсия', 'Пенсия'),
        ('стипендия', 'Стипендия'),
        ('выигрыш', 'Выигрыш'),
        ('доходы от индивидуальной предпринимательской деятельности',
         'Доходы от индивидуальной предпринимательской деятельности'),
        ('доходы от недвижимости', 'Доходы от недвижимости'),
        ('доходы от депозита', 'Доходы от депозита'),
        ('подарки', 'Подарки'),
        ('наличные денежные средства', 'Наличные денежные средства'),
        ('прочие доходы', 'Прочие доходы'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    income_type = models.CharField(max_length=100, choices=INCOME_TYPES)
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))])
    date = models.DateField()

    def __str__(self):
        return f"{self.income_type} - {self.amount}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class SubSubCategory(models.Model):
    name = models.CharField(max_length=100)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    subsubcategory = models.ForeignKey(SubSubCategory, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return f"{self.category} - {self.subcategory} - {self.subsubcategory} - {self.amount}"


class CarExpense(models.Model):
    car_brand = models.CharField(max_length=100)
    mileage = models.PositiveIntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=250)
    date = models.DateField()
    subsubcategory = models.ForeignKey(Expense, on_delete=models.CASCADE, related_name='car_expenses')

    def __str__(self):
        return f"{self.car_brand} - {self.amount}"


class PlannedExpense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=255)
    start_date = models.DateField()

    item_cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))]
    )

    months_to_save = models.IntegerField(
        validators=[MinValueValidator(1)]
    )

    monthly_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True
    )

    def calculate_monthly_amount(self):
        if self.months_to_save > 0:
            return self.item_cost / self.months_to_save
        return Decimal('0.00')

    def save(self, *args, **kwargs):
        self.monthly_amount = self.calculate_monthly_amount()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.item_name} - {self.item_cost}"


class Credit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    credit_name = models.CharField(max_length=255)
    credit_amount = models.PositiveIntegerField()
    credit_term = models.IntegerField()
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    issue_date = models.DateField()

    def __str__(self):
        return self.credit_name

    @property
    def principal_amount(self):
        return Decimal(self.credit_amount) / Decimal(self.credit_term)

    @property
    def monthly_interest(self):
        return (Decimal(self.credit_amount) * (self.interest_rate / Decimal(100))) / Decimal(12)

    @property
    def monthly_payment(self):
        return self.principal_amount + self.monthly_interest

djProjHomrBuhWeb/homebuhweb/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import CarExpense
from .models import Expense
from .models import Profile, PlannedExpense, Credit


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'phone', 'address']
        labels = {
            'avatar': 'Аватар',
            'phone': 'Телефон',
            'address': 'Адрес',
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Электронная почта',
        }


class ExpenseForm(forms.ModelForm):
    subsubcategory_id = forms.CharField(
        label='ID Подподкатегории',
        required=False,
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    class Meta:
        model = Expense
        fields = ['category', 'subcategory', 'subsubcategory', 'subsubcategory_id', 'amount', 'date']

    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)

        if self.instance and self.instance.pk:
            self.fields['subsubcategory_id'].initial = self.instance.subsubcategory.id

        self.fields['amount'].widget.attrs.update({'min': '0', 'step': '0.01'})

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')

        if amount < 0:
            raise forms.ValidationError('Сумма не может быть отрицательной')
        return amount


class CarExpenseForm(forms.ModelForm):
    class Meta:
        model = CarExpense
        fields = ['car_brand', 'mileage', 'amount', 'description', 'date']
        labels = {
            'car_brand': 'Марка автомобиля',
            'mileage': 'Пробег',
            'amount': 'Сумма',
            'description': 'Описание товара',
            'date': 'Дата',
        }
        widgets = {
            'car_brand': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #ffffff;'}),
            'mileage': forms.NumberInput(attrs={'class': 'form-control', 'style': 'background-color: #ffffff;'}),
            'amount': forms.NumberInput(attrs={
                'class': 'form-control',
                'readonly': 'readonly',
                'style': 'background-color: #A78B71; color: #ffffff;'
            }),
            'description': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #ffffff;'}),
            'date': forms.TextInput(attrs={
                'class': 'form-control',
                'readonly': 'readonly',
                'style': 'background-color: #A78B71; color: #ffffff;'
            }),
        }


class PlannedExpenseForm(forms.ModelForm):
    class Meta:
        model = PlannedExpense
        fields = ['item_name', 'start_date', 'item_cost', 'months_to_save']

        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
        }

        labels = {
            'item_name': 'Наименование планируемой покупки',
            'start_date': 'Дата начала накопления',
            'item_cost': 'Стоимость покупки',
            'months_to_save': 'Количество месяцев за которые нужно накопить',
        }


class CreditForm(forms.ModelForm):
    class Meta:
        model = Credit
        fields = ['credit_name', 'credit_amount', 'credit_term', 'interest_rate', 'issue_date']
        widgets = {
            'issue_date': forms.DateInput(attrs={'type': 'date'}),
        }
        labels = {
            'credit_name': 'Название кредита',
            'credit_amount': 'Сумма кредита',
            'credit_term': 'Срок кредита',
            'interest_rate': 'Процентная ставка',
            'issue_date': 'Дата выдачи',
        }

homebuhweb/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import CarExpense
from .models import Expense
from .models import Profile, PlannedExpense, Credit


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'phone', 'address']
        labels = {
            'avatar': 'Аватар',
            'phone': 'Телефон',
            'address': 'Адрес',
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Электронная почта',
        }





from django import forms
from .models import Expense

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['category', 'subcategory', 'subsubcategory', 'amount', 'date']

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount < 0:
            raise forms.ValidationError('Сумма не может быть отрицательной')
        return amount





class CarExpenseForm(forms.ModelForm):
    class Meta:
        model = CarExpense
        fields = ['car_brand', 'mileage', 'amount', 'description', 'date']
        labels = {
            'car_brand': 'Марка автомобиля',
            'mileage': 'Пробег',
            'amount': 'Сумма',
            'description': 'Описание товара',
            'date': 'Дата',
        }
        widgets = {
            'car_brand': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #ffffff;'}),
            'mileage': forms.NumberInput(attrs={'class': 'form-control', 'style': 'background-color: #ffffff;'}),
            'amount': forms.NumberInput(attrs={
                'class': 'form-control',
                'readonly': 'readonly',
                'style': 'background-color: #A78B71; color: #ffffff;'
            }),
            'description': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #ffffff;'}),
            'date': forms.TextInput(attrs={
                'class': 'form-control',
                'readonly': 'readonly',
                'style': 'background-color: #A78B71; color: #ffffff;'
            }),
        }


class PlannedExpenseForm(forms.ModelForm):
    class Meta:
        model = PlannedExpense
        fields = ['item_name', 'start_date', 'item_cost', 'months_to_save']

        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
        }

        labels = {
            'item_name': 'Наименование планируемой покупки',
            'start_date': 'Дата начала накопления',
            'item_cost': 'Стоимость покупки',
            'months_to_save': 'Количество месяцев за которые нужно накопить',
        }


class CreditForm(forms.ModelForm):
    class Meta:
        model = Credit
        fields = ['credit_name', 'credit_amount', 'credit_term', 'interest_rate', 'issue_date']
        widgets = {
            'issue_date': forms.DateInput(attrs={'type': 'date'}),
        }
        labels = {
            'credit_name': 'Название кредита',
            'credit_amount': 'Сумма кредита',
            'credit_term': 'Срок кредита',
            'interest_rate': 'Процентная ставка',
            'issue_date': 'Дата выдачи',
        }

templates/homebuhweb/credit/add_credit.html
{% extends 'homebuhweb/base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">{% if credit %}Изменить кредит/рассрочку{% else %}Добавить
            кредит/рассрочку{% endif %}</h2>
        <form method="post" class="mx-auto" style="max-width: 600px;">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_credit_name" class="form-label">Наименование кредита/рассрочки</label>
                <input type="text" name="credit_name" id="id_credit_name" class="form-control"
                       value="{{ credit.credit_name }}" required>
            </div>
            <div class="mb-3">
                <label for="id_credit_amount" class="form-label">Сумма кредита/рассрочки</label>
                <input type="number" name="credit_amount" id="id_credit_amount" class="form-control" min="0" step="0.01"
                       value="{{ credit.credit_amount }}" required>
            </div>
            <div class="mb-3">
                <label for="id_credit_term" class="form-label">Срок кредита/рассрочки (в месяцах)</label>
                <input type="number" name="credit_term" id="id_credit_term" class="form-control" min="0"
                       value="{{ credit.credit_term }}" required>
            </div>
            <div class="mb-3">
                <label for="id_interest_rate" class="form-label">Процентная ставка</label>
                <input type="number" name="interest_rate" id="id_interest_rate" class="form-control" min="0" step="0.01"
                       value="{{ credit.interest_rate }}" required>
            </div>
            <div class="mb-3">
                <label for="id_issue_date" class="form-label">Дата выдачи</label>
                <input type="date" name="issue_date" id="id_issue_date" class="form-control"
                       value="{{ credit.issue_date }}" required>
            </div>
            <button type="submit" class="btn btn-custom my-2">Рассчитать и сохранить</button>
            <a href="{% url 'user_cabinet' %}" class="btn btn-custom my-2">Вернуться в личный кабинет</a>
        </form>
        <div id="calculation-results" class="mt-4" style="display: none;">
            <h4>Результаты расчета</h4>
            <p>Сумма по основному долгу: <span id="principal-amount"></span></p>
            <p>Сумма процентов в месяц: <span id="monthly-interest"></span></p>
            <p>Общая сумма платежа в месяц: <span id="monthly_payment"></span></p>
        </div>
    </div>

    <div class="container mt-5">
        <h2 class="text-center mb-4">Сохраненные кредиты/рассрочки</h2>
        <h6>Сумма всех платежей в месяц (приблизительно): {{ total_monthly_payments|floatformat:2 }}</h6>
        <table class="table table-striped text-center">
            <thead>
            <tr>
                <th>Наименование</th>
                <th>Дата выдачи</th>
                <th>Сумма</th>
                <th>Процентная ставка</th>
                <th>Срок (мес.)</th>
                <th>Сумма по основному долгу</th>
                <th>Сумма процентов в месяц</th>
                <th>Общая сумма платежа в месяц</th>
                <th>Операции</th>
            </tr>
            </thead>
            <tbody>
            {% for credit in credits %}
                <tr {% if credit.is_paid_off %}style="background-color: #AEC670;"{% endif %}>
                    <td>{{ credit.credit_name }}</td>
                    <td>{{ credit.issue_date|date:"d.m.Y" }}</td>
                    <td>{{ credit.credit_amount|floatformat:2 }}</td>
                    <td>{{ credit.interest_rate|floatformat:2 }}%</td>
                    <td>{{ credit.credit_term }}</td>
                    <td>{{ credit.principal_amount|floatformat:2 }}</td>
                    <td>{{ credit.monthly_interest|floatformat:2 }}</td>
                    <td>{{ credit.monthly_payment|floatformat:2 }}</td>
                    <td>
                        <a href="{% url 'edit_credit' credit.id %}" class="btn btn-custom btn-sm">Изменить</a>
                        <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal"
                                data-credit-id="{{ credit.id }}" data-credit-name="{{ credit.credit_name }}">Удалить
                        </button>
                        {% if not credit.is_paid_off %}
                            <form method="post" action="{% url 'mark_as_paid_off' credit.id %}" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success btn-sm">Кредит погашен</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Удалить кредит/рассрочку</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Вы уверены, что хотите удалить кредит/рассрочку "<span id="modal-credit-name"></span>"?</p>
                </div>
                <div class="modal-footer">
                    <form method="post" action="{% url 'delete_credit' %}" id="delete-form">
                        {% csrf_token %}
                        <input type="hidden" name="credit_id" id="modal-credit-id">
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var deleteModal = document.getElementById('deleteModal');
            deleteModal.addEventListener('show.bs.modal', function (event) {
                var button = event.relatedTarget;
                var creditId = button.getAttribute('data-credit-id');
                var creditName = button.getAttribute('data-credit-name');
                var modalCreditName = deleteModal.querySelector('#modal-credit-name');
                var modalCreditId = deleteModal.querySelector('#modal-credit-id');
                modalCreditName.textContent = creditName;
                modalCreditId.value = creditId;
            });
        });
    </script>

    <script src="{% static 'js/homepage_script.js' %}"></script>
{% endblock %}